import{a as S,S as v,i as s}from"./assets/vendor-CyQxvrJ3.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))c(e);new MutationObserver(e=>{for(const t of e)if(t.type==="childList")for(const n of t.addedNodes)n.tagName==="LINK"&&n.rel==="modulepreload"&&c(n)}).observe(document,{childList:!0,subtree:!0});function i(e){const t={};return e.integrity&&(t.integrity=e.integrity),e.referrerPolicy&&(t.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?t.credentials="include":e.crossOrigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function c(e){if(e.ep)return;e.ep=!0;const t=i(e);fetch(e.href,t)}})();const $="https://pixabay.com/api/",q="54395192-1d301966f0221603052d26baa",P=15;async function u(r,o){return(await S.get($,{params:{key:q,q:r,image_type:"photo",orientation:"horizontal",safesearch:!0,page:o,per_page:P}})).data}const f=document.querySelector(".gallery"),m=document.querySelector(".loader"),h=document.querySelector(".load-more"),B=new v(".gallery a",{captionsData:"alt",captionDelay:250});function y(r){const o=r.map(({webformatURL:i,largeImageURL:c,tags:e,likes:t,views:n,comments:w,downloads:E})=>`
      <li class="gallery-item">
        <a href="${c}">
          <img src="${i}" alt="${e}" loading="lazy" />
        </a>
        <div class="info">
          <p><b>Likes:</b> ${t}</p>
          <p><b>Views:</b> ${n}</p>
          <p><b>Comments:</b> ${w}</p>
          <p><b>Downloads:</b> ${E}</p>
        </div>
      </li>
    `).join("");f.insertAdjacentHTML("beforeend",o),B.refresh()}function M(){f.innerHTML=""}function g(){m.classList.remove("hidden")}function p(){m.classList.add("hidden")}function A(){h.classList.remove("hidden")}function L(){h.classList.add("hidden")}const H=document.querySelector(".form"),O=document.querySelector(".load-more"),_=document.querySelector(".gallery");let l="",a=1,d=0;const b=15;H.addEventListener("submit",x);O.addEventListener("click",I);async function x(r){if(r.preventDefault(),l=r.target.elements["search-text"].value.trim(),!!l){a=1,M(),L(),g();try{const o=await u(l,a);if(d=o.totalHits,o.hits.length===0){s.error({message:"Sorry, there are no images matching your search query."});return}y(o.hits),s.success({message:`Hooray! We found ${d} images.`}),d>b&&A()}catch{s.error({message:"Something went wrong 😢"})}finally{p()}}}async function I(){a+=1,g();try{const r=await u(l,a);y(r.hits),D(),a*b>=d&&(L(),s.info({message:"We're sorry, but you've reached the end of search results."}))}catch{s.error({message:"Load more failed 😢"})}finally{p()}}function D(){const r=_.firstElementChild.getBoundingClientRect().height;window.scrollBy({top:r*2,behavior:"smooth"})}
//# sourceMappingURL=index.js.map
